### ISSUE TITLE
Add documentation for Project Token routes

### ISSUE THREAD

**Issue by tyrw** [anymod/uf-docs#3]
The scaffolding for the docs has been set up, but the content is still mostly dummy text.  We want to add some documentation for the Project Token routes from the [spreadsheet](https://docs.google.com/spreadsheets/d/1lE4vyTwZgwmbRMruOCdQk8ebwV8ZsahPsp4T8ho6s08/edit#gid=1518685593)

```
POST	/users
POST	/users/createOrUpdate
POST	/users/invite
POST	/users/find (already mostly done)
PUT	/users/active
```

Each route should have a high level overview (1-2 sentences) about what it does, as well as an example curl request and JS request in the example section (right side).

Can do rolling deploys for docs -- no need for code reviews to block.

https://docs.userfront.com/#users

**Comment by damionvega** [comment]
Updates are in!
